version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    # restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
  redis:
    container_name: redis
    image: 'redis:alpine'
    command: redis-server --requirepass admin
    ports:
      - '6379:6379'
